Branch for testing threads
AntonPanchishko/ThreadProject pull request #1
Opened 2021-02-22 16:04 UTC by AntonPanchishko

2021-02-22 21:53 UTC, Max-Pochepets requested changes

2021-02-22 21:53 UTC, Max-Pochepets commented on src/main/java/Main.java
> +        Counter counterForThread = new Counter();
You should have one Counter for both threads

2021-02-22 21:53 UTC, Max-Pochepets commented on src/main/java/Counter.java
> +    }
Let's leave `getCount()` as a normal counter and make a separate `increment()` method to increase count value

2021-02-22 21:53 UTC, Max-Pochepets commented on src/main/java/RunnableClass.java
> +        }
You have Counter. What for do you need for loop?

2021-02-23 11:51 UTC, Max-Pochepets approved these changes

2021-02-23 11:56 UTC, Sofasmile commented on src/main/java/Main.java
> +        threadClass.run();
what is the difference between start() and run()?

2021-02-23 12:06 UTC, AntonPanchishko commented on src/main/java/Main.java
> +        threadClass.run();
As I anderstanded, start() we use for classes which immplement interface Runnable 
and run() we use for classes which extend Thread

2021-02-23 14:11 UTC, Sofasmile commented on src/main/java/Main.java
> +        threadClass.run();
не зовсім так
start() запускає виконання в новому потоці, а run() запускає виконання в поточному потоці, тобто в тому потоці що main

2021-02-23 14:11 UTC, Sofasmile approved these changes

2021-02-23 16:06 UTC, merged